export const ROUTES = {
  HOME: "/dashboard",
  ME: "/me",
  LOGIN: "/login",
  LOGIN_PAGE: "/",
  REGISTER: "/auth/register",
  SETTINGS: "/settings",
  HELP_CENTER: "/helpcenter",
  FORMS: "/forms",
  FAQ: "/faqs",
  ARTICLEPAGE:"/article-page",
  FORMPAGE:"/form-page",
  ABOUT: "/about",
  ARTICLE: "/articles",
  ARTICLE_CREATE: "/articles/create",
  ARTICLE_VIEW: "/articles/:articleId",
  ARTICLE_EDIT: "/articles/:articleId/edit",
  ARTICLE_CATEGORY_CREATE: "/article-category/create",
  ARTICLE_CATEGORY: "/article-categories",
  ARTICLE_CATEGORY_VIEW: "/article-category/:categoryId",
  ARTICLE_CATEGORY_EDIT: "/article-category/:categoryId/edit",
  HOMEPAGE: "/homepage",
  PARTNER: "/partner",
  TERM_OF_SERVICE: "/term-of-service",
  PRIVACY_POLICY: "/privacy-policy",
  EMAIL_TEMPLATES: "/email-templates",
  COUNTY: "/counties",
  COUNTY_CREATE: "/county/create",
  COUNTY_VIEW: "/county/:countyId",
  COUNTY_EDIT: "/county/:countyId/Edit",


  CITIES: "/counties",
  PLACES: "/places",
  PLACES_CREATE: "/places/create",
  PLACES_VIEW: "/place/:placeId",
  PLACES_EDIT: "/place/:placeId/Edit",
  COMPANIES: "/companies",
  COMPANIES_CREATE: "/companies/create",
  COMPANIES_VIEW: "/company/:companyId",
  COMPANIES_EDIT: "/company/:companyId/Edit",

  FOOTER: "/footer",
  FOOTER_CREATE: "footer/create/:tab",
  FOOTER_VIEW: "footer/create/articles/select",
  FOOTER_EDIT: "footer/edit/:tab/:index",
  FOOTER_EDIT_FOR_HEADER_AND_ADDRESS: "footer/edit/:tab/",
  

  FAQPAGE :"/faq-page",


  COUNTIES: "/counties",
  QUOTES: "/quotes",
  REAL_ESTATE_AGENTS: "/real-estate-agents",
  REAL_ESTATE_AGENTS_EDIT: "/real-estate-agent/:agentId/edit",
  REAL_ESTATE_AGENTS_EDIT: "/real-estate-agent/:id/edit",

  SITEMAP:"/sitemap",
  CONTACTUS:"/contact",
  CONTACTUS_VIEW :"/contact/:id",

  COUNTIES: "/counties",
  QUOTES: "/quotes",
  PARTNERS: "/partners",
  PARTNER_CREATE: "/partners/create",
  PARTNERS_ID: "/partners/:id",
  PARTNERS_EDIT_ID: "/partners/:id/edit",
  PARTNERS_VIEW_LOGS :"/partners/view-logs/:partnerId",

  LEAD_LOGS :"/lead-logs"
};
